apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: train-schedule-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: train-schedule-app
    spec:
      containers:
      - name: train-schedule-app-container
        image: $dockerhub_repo:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
   name: train-schedule-service
spec:
  selector:
    app: train-schedule-app
  ports:
   - name: http 
     protocol: TCP
     port: 8080
     targetPort: 8080
  type: NodePort         